#The program calculates how many 6 letter words can be generated by switching symbols in a word "НЕБО“ （or any other word instead)
import itertools
k = 0
a = list(itertools.permutations("НЕБО"))
print(len(set(a)))
